import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const u = (...codes) => String.fromCharCode(...codes);

const si = {
  walin: u(0x0dc0, 0x0dbd, 0x0dd2, 0x0db1, 0x0dca),
  karamu: u(0x0d9a, 0x0dbb, 0x0db8, 0x0dd4),
  saha: u(0x0dc3, 0x0dc4),
  ekama: u(0x0d91, 0x0d9a, 0x0db8),
  eken: u(0x0d91, 0x0d9a, 0x0dd9, 0x0db1, 0x0dca),
  eke: u(0x0d91, 0x0d9a, 0x0dda),
  eka: u(0x0d91, 0x0d9a),
  ekak: u(0x0d91, 0x0d9a, 0x0d9a, 0x0dca),
  ekata: u(0x0d91, 0x0d9a, 0x0da7),
  vidihata: u(0x0dc0, 0x0dd2, 0x0daf, 0x0dd2, 0x0dc4, 0x0da7),
  karanna: u(0x0d9a, 0x0dbb, 0x0db1, 0x0dca, 0x0db1),
  puluwan: u(0x0db4, 0x0dd4, 0x0dc5, 0x0dd4, 0x0dc0, 0x0db1, 0x0dca),
  thiyenawada: u(0x0dad, 0x0dd2, 0x0dba, 0x0dd9, 0x0db1, 0x0dc0, 0x0daf),
  wenna: u(0x0dc0, 0x0dd9, 0x0db1, 0x0dca, 0x0db1),
  aluth: u(0x0d85, 0x0dbd, 0x0dd4, 0x0dad, 0x0dca),
  kenekda: u(0x0d9a, 0x0dd9, 0x0db1, 0x0dd9, 0x0d9a, 0x0dca, 0x0daf),
  hadanna: u(0x0dc4, 0x0daf, 0x0db1, 0x0dca, 0x0db1),
  ayeth: u(0x0d86, 0x0dba, 0x0dd9, 0x0dad, 0x0dca),
  tika: u(0x0da7, 0x0dd2, 0x0d9a),
  karala: u(0x0d9a, 0x0dbb, 0x0dbd, 0x0dcf),
  nehae: u(0x0db1, 0x0dd0, 0x0dc4, 0x0dd0),
  una: u(0x0d8b, 0x0db1, 0x0dcf),
  wenawa: u(0x0dc0, 0x0dd9, 0x0db1, 0x0dc0, 0x0dcf),
  okkoma: u(0x0d94, 0x0d9a, 0x0dca, 0x0d9a, 0x0ddc, 0x0db8),
  kata: u(0x0d9a, 0x0da7),
  wada: u(0x0dc0, 0x0da9, 0x0dcf),
  ona: u(0x0d95, 0x0db1),
  ilagata: u(0x0d8a, 0x0dc5, 0x0d9f, 0x0da7),
  me: u(0x0db8, 0x0dda),
  hadenawa: u(0x0dc4, 0x0dd0, 0x0daf, 0x0dd9, 0x0db1, 0x0dc0, 0x0dcf),
  mona: u(0x0db8, 0x0ddc, 0x0db1),
  wath: u(0x0dc0, 0x0dad, 0x0dca),
  ahanna: u(0x0d85, 0x0dc4, 0x0db1, 0x0dca, 0x0db1),
  ho: u(0x0dc4, 0x0ddd),
  deela: u(0x0daf, 0x0dd3, 0x0dbd, 0x0dcf),
  oyage: u(0x0d94, 0x0dba, 0x0dcf, 0x0d9c, 0x0dda),
  hari: u(0x0dc4, 0x0dbb, 0x0dd2),
  mama: u(0x0db8, 0x0db8),
  dannawa: u(0x0daf, 0x0db1, 0x0dca, 0x0db1, 0x0dc0, 0x0dcf),
  balanna: u(0x0db6, 0x0dbd, 0x0db1, 0x0dca, 0x0db1),
  nawatha: u(0x0db1, 0x0dd0, 0x0dc0, 0x0dad),
  unoth: u(0x0d8b, 0x0db1, 0x0ddc, 0x0dad, 0x0dca),
  yanna: u(0x0dba, 0x0db1, 0x0dca, 0x0db1),
  sin: u(0x0dc3, 0x0dd2, 0x0d82),
  enawa: u(0x0d91, 0x0db1, 0x0dc0, 0x0dcf),
  mage: u(0x0db8, 0x0d9c, 0x0dda),
  durwala: u(0x0daf, 0x0dd4, 0x0dbb, 0x0dca, 0x0dc0, 0x0dbd),
  ugannwanna: u(0x0d8b, 0x0d9c, 0x0db1, 0x0dca, 0x0dc0, 0x0db1, 0x0dca, 0x0db1),
  ada: u(0x0d85, 0x0daf),
  balala: u(0x0db6, 0x0dbd, 0x0dbd, 0x0dcf),
  wenas: u(0x0dc0, 0x0dd9, 0x0db1, 0x0dc3, 0x0dca),
  dawasa: u(0x0daf, 0x0dc0, 0x0dc3),
  nemei: u(0x0db1, 0x0dd9, 0x0db8, 0x0dd9, 0x0dba, 0x0dd2),
  ewa: u(0x0d92, 0x0dc0, 0x0dcf),
  aluthen: u(0x0d85, 0x0dbd, 0x0dd4, 0x0dad, 0x0dd9, 0x0db1, 0x0dca),
  hema: u(0x0dc4, 0x0dd0, 0x0db8),
  dawasama: u(0x0daf, 0x0dc0, 0x0dc3, 0x0db8),
  gaththa: u(0x0d9c, 0x0dad, 0x0dca, 0x0dad),
  vidiha: u(0x0dc0, 0x0dd2, 0x0daf, 0x0dd2, 0x0dc4),
  wisthara: u(0x0dc0, 0x0dd2, 0x0dc3, 0x0dca, 0x0dad, 0x0dbb),
  kirima: u(0x0d9a, 0x0dd2, 0x0dbb, 0x0dd3, 0x0db8),
  padama: u(0x0db4, 0x0dcf, 0x0da9, 0x0db8),
  padam: u(0x0db4, 0x0dcf, 0x0da9, 0x0db8, 0x0dca),
  kotasa: u(0x0d9a, 0x0ddc, 0x0da7, 0x0dc3),
  iwarayi: u(0x0d89, 0x0dc0, 0x0dbb, 0x0dba, 0x0dd2),
  parak: u(0x0db4, 0x0dcf, 0x0dbb, 0x0d9a, 0x0dca),
  witharayi: u(0x0dc0, 0x0dd2, 0x0dad, 0x0dbb, 0x0dba, 0x0dd2),
  dawasata: u(0x0daf, 0x0dc0, 0x0dc3, 0x0da7),
  kihipayak: u(
    0x0d9a,
    0x0dd2,
    0x0dc4,
    0x0dd2,
    0x0db4,
    0x0dba,
    0x0d9a,
    0x0dca,
  ),
  mahansi: u(0x0db8, 0x0dc4, 0x0db1, 0x0dca, 0x0dc3, 0x0dd2),
  niyama: u(0x0db1, 0x0dd2, 0x0dba, 0x0db8),
  kotasa: u(0x0d9a, 0x0ddc, 0x0da7, 0x0dc3),
  amarui: u(0x0d85, 0x0db8, 0x0dcf, 0x0dbb, 0x0dd4, 0x0dba, 0x0dd2),
  hadala: u(0x0dc4, 0x0daf, 0x0dbd, 0x0dcf),
  denna: u(0x0daf, 0x0dd9, 0x0db1, 0x0dca, 0x0db1),
  wage: u(0x0dc0, 0x0d9c, 0x0dda),
  therenne: u(
    0x0dad,
    0x0dda,
    0x0dbb,
    0x0dd9,
    0x0db1,
    0x0dca,
    0x0db1,
    0x0dda,
  ),
};

const singlish = {
  appName: "StudyGenie",
  tagline: `StudyGenie ${si.walin} lesson ${si.eka} easy ${si.karamu}`,
  welcomeBody: `AI Tutor, notes, quizzes, ${si.saha} flashcards ${si.ekama} app ${si.eken}. Phone ${si.eke} PWA ${si.vidihata} install ${si.karanna} ${si.puluwan}.`,
  startLearning: `Start ${si.karanna}`,
  alreadyHaveAccount: `Account ${si.ekak} ${si.thiyenawada}?`,
  login: `Login ${si.wenna}`,
  signup: `Signup ${si.wenna}`,
  noAccount: `${si.aluth} user ${si.kenekda}?`,
  createAccount: `Account ${si.eka} ${si.hadanna}`,
  email: `Email ${si.eka}`,
  password: `Password ${si.eka}`,
  name: `Name ${si.eka}`,
  grade: `Grade / Level ${si.eka}`,
  subjects: "Subjects",
  loginTitle: `${si.ayeth} welcome`,
  loginHint: `Email ${si.saha} password ${si.eken} login ${si.wenna}.`,
  signupTitle: `${si.aluth} account ${si.eka}`,
  signupHint: `Details ${si.tika} fill ${si.karala} start ${si.karanna}.`,
  demoMode: `Supabase keys ${si.nehae}. Demo mode ${si.eke} local account ${si.eken} continue ${si.karanna} ${si.puluwan}.`,
  supabaseReady: `Supabase link ${si.una}. Real accounts save ${si.wenawa}.`,
  invalidLogin: `Email or password ${si.eka} wrong. ${si.ayeth} try ${si.karanna}.`,
  fillRequired: `Required fields ${si.okkoma} fill ${si.karanna}.`,
  weakPassword: `Password ${si.eka} characters 6${si.kata} ${si.wada} ${si.wenna} ${si.ona}.`,
  homeTitle: "Home",
  homeHello: "Hello",
  continueLearning: "Continue learning",
  todayStreak: "Streak",
  days: "days",
  lastQuiz: "Last quiz",
  noQuizYet: `Quiz ${si.ekak} try ${si.karala} ${si.nehae}. ${si.ilagata} ${si.eka} start ${si.karanna}.`,
  quickActions: "Quick actions",
  tutor: "AI Tutor",
  notes: "Notes",
  quiz: "Quiz",
  flashcards: "Flashcards",
  uploads: "Uploads",
  profile: "Profile",
  tutorTitle: "AI Tutor",
  tutorHint: `Class ${si.eken} ${si.nemei}. ${si.oyage} results, papers, ${si.saha} ${si.durwala} subjects ${si.balala} ${si.ugannwanna}.`,
  tutorPlaceholder: `Weak topic ${si.eka} type ${si.karanna}, ${si.ho} results ${si.eken} start ${si.karanna}...`,
  send: `Send ${si.karanna}`,
  thinking: `Answer ${si.eka} ${si.hadenawa}...`,
  newChat: `${si.aluth} chat ${si.eka}`,
  emptyTutor: `${si.oyage} quiz results, papers, ${si.saha} subjects ${si.balala}, ${si.durwala} ${si.ewa} ${si.ugannwanna}.`,
  startFromResults: `Results ${si.eken} start ${si.karanna}`,
  startFromResultsPrompt: `${si.mage} quiz results, papers, ${si.saha} ${si.durwala} subjects ${si.balala}, ${si.durwala} ${si.ewa} ${si.ugannwanna}.`,
  notesTitle: "Notes",
  notesHint: `Topic ${si.eka} ${si.deela}, ${si.oyage} results ${si.saha} papers ${si.balala} notes ${si.hadanna}.`,
  topic: `Topic ${si.eka}`,
  sourceText: "Extra text / lesson extract",
  generateNotes: `Notes generate ${si.karanna}`,
  saveNote: `Note ${si.eka} save ${si.karanna}`,
  notesEmpty: `Saved notes ${si.nehae}. ${si.aluth} note ${si.ekak} ${si.hadanna}.`,
  notesSaved: `Notes save ${si.una}. Revision ${si.ekata} use ${si.karanna}.`,
  generating: `Generate ${si.wenawa}...`,
  quizTitle: "Quiz",
  quizHint: `${si.oyage} subjects ${si.saha} miss ${si.una} ${si.ewa} practice ${si.karanna}.`,
  generateQuiz: `Quiz ${si.eka} ${si.hadanna}`,
  startQuiz: `Quiz ${si.eka} start ${si.karanna}`,
  nextQuestion: `Next question ${si.eka}`,
  seeScore: `Score ${si.eka} ${si.balanna}`,
  yourScore: `${si.oyage} score ${si.eka}`,
  tryAgain: `${si.ayeth} try ${si.karanna}`,
  newQuiz: `${si.aluth} quiz ${si.eka}`,
  quizEmpty: `Topic ${si.ekak} ${si.deela} quiz ${si.eka} generate ${si.karanna}.`,
  correct: si.hari,
  wrong: "Wrong",
  flashTitle: "Flashcards",
  flashHint: `${si.durwala} areas ${si.saha} papers ${si.walin} cards ${si.hadanna}.`,
  generateCards: `Cards generate ${si.karanna}`,
  flip: `Card ${si.eka} flip ${si.karanna}`,
  iKnow: `${si.mama} ${si.dannawa}`,
  reviewAgain: `${si.ayeth} ${si.balanna} ${si.ona}`,
  flashEmpty: `Cards ${si.nehae}. Topic ${si.ekak} ${si.deela} generate ${si.karanna}.`,
  uploadsTitle: "Uploads",
  uploadsHint: `NIE syllabus ${si.ho} teacher-guide PDF / TXT upload ${si.karala} AI ${si.ekata} index ${si.karanna}. Maximum 8MB. HTML/JS files ${si.nehae}.`,
  pickFile: `File ${si.eka} select ${si.karanna}`,
  fileTitle: `Title ${si.eka}`,
  saveUpload: `Upload ${si.eka} save ${si.karanna}`,
  uploadsEmpty: `Uploaded files ${si.nehae}.`,
  uploadSaved: `File save ${si.una}.`,
  noFile: `${si.ilagata} file ${si.ekak} select ${si.karanna}.`,
  fileTooBig: `File ${si.eka} 8MB ${si.wada}. Podi file ${si.ekak} select ${si.karanna}.`,
  fileTypeBlocked: `Me file type ${si.eka} allow ${si.nehae}. PDF, TXT, MD, DOC, DOCX witharak.`,
  fileUnsafe: `Me file ${si.eke} script / HTML thiyenawa. Upload ${si.karanna} ${si.nehae}.`,
  somethingWentWrong: `Error ${si.ekak} ${si.una}. ${si.ayeth} try ${si.karanna}.`,
  invalidName: `Name ${si.eka} hariyata type ${si.karanna}.`,
  invalidEmail: `Email ${si.eka} hariyatama type ${si.karanna}.`,
  profileTitle: "Profile",
  saveProfile: `Profile ${si.eka} save ${si.karanna}`,
  logout: `Logout ${si.wenna}`,
  profileSaved: `Profile update ${si.una}.`,
  languageMix: "App language",
  singlish: `${si.sin}shish`,
  english: "English",
  offlineTitle: "Offline",
  offlineBody: `Network ${si.nehae}. Connection ${si.eka} ${si.nawatha} check ${si.karala} try ${si.karanna}. Home ${si.eka} cache ${si.unoth} open ${si.karanna} ${si.puluwan}.`,
  goHome: `Home ${si.ekata} ${si.yanna}`,
  installHint: `Phone ${si.eke} Share / Menu ${si.eken} Add to Home Screen select ${si.karanna}.`,
  mockAiBanner: `AI key ${si.nehae} \u2014 demo answers ${si.enawa}. Real AI later link ${si.karanna}.`,
  subjectsHint: `Comma ${si.walin} subjects type ${si.karanna}. Ex: Maths, Science, English`,
  navHome: "Home",
  navTutor: "Tutor",
  navNotes: "Notes",
  navQuiz: "Quiz",
  navMe: "Me",
  classGenie: "ClassGenie",
  openMenu: `Menu ${si.eka} open ${si.karanna}`,
  closeMenu: `Menu ${si.eka} close ${si.karanna}`,
  menuTitle: "Menu",
  teacherHome: `Teacher home`,
  teacherHomeHint: `Classes, students, assignments, ${si.saha} daily questions manage ${si.karanna}.`,
  classes: "Classes",
  students: "Students",
  assignments: "Assignments",
  classesEmpty: `Classes ${si.nehae}. ${si.aluth} class ${si.ekak} add ${si.karanna}.`,
  studentsEmpty: `Students ${si.nehae}.`,
  assignmentsEmpty: `Assignments ${si.nehae}.`,
  classesHint: `${si.oyage} classes add ${si.karala} students ${si.saha} assignments ${si.ekata} link ${si.karanna}.`,
  studentsHint: `Class ${si.ekak} select ${si.karala} student add ${si.karanna}.`,
  assignmentsHint: `Class ${si.ekak} ${si.ekata} homework / assignment ${si.ekak} add ${si.karanna}.`,
  addClass: `${si.aluth} class ${si.ekak} add ${si.karanna}`,
  editClass: `Class ${si.eka} edit ${si.karanna}`,
  saveClass: `Class ${si.eka} save ${si.karanna}`,
  className: `Class name ${si.eka}`,
  classSaved: `Class save ${si.una}.`,
  selectClass: `Class ${si.eka} select ${si.karanna}`,
  noClassYet: `Mulin class ${si.ekak} add ${si.karanna}.`,
  addStudent: `Student add ${si.karanna}`,
  saveStudent: `Student save ${si.karanna}`,
  studentSaved: `Student save ${si.una}.`,
  addAssignment: `Assignment add ${si.karanna}`,
  saveAssignment: `Assignment save ${si.karanna}`,
  assignmentTitle: `Assignment title ${si.eka}`,
  assignmentDetails: "Details",
  assignmentDue: "Due date",
  assignmentSaved: `Assignment save ${si.una}.`,
  previewFile: `Preview ${si.karanna}`,
  downloadFile: `Download ${si.karanna}`,
  deleteFile: `File ${si.eka} delete ${si.karanna}`,
  useInNotes: `Notes ${si.ekata} use ${si.karanna}`,
  fileExtractEmpty: `Me file ${si.eke} text preview ${si.nehae}. PDF / TXT / MD ${si.eken} AI ${si.ekata} index ${si.karanna} ${si.puluwan}.`,
  indexForAi: `AI ${si.ekata} index ${si.karanna}`,
  indexingSource: `Index ${si.wenawa}...`,
  sourceIndexed: `AI source ${si.ekata} index ${si.una}`,
  sourceIndexEmpty: `Me file ${si.eken} text ${si.nehae}. PDF / TXT / MD ${si.eken} try ${si.karanna}.`,
  studentApp: "StudyGenie",
  teacherApp: "ClassGenie",
  profileAria: "Profile",
  yearBar: "Calendar year",
  yearBarHint: `Day {day} / {days} \u2014 {year} calendar ${si.eka}`,
  addEvent: `Event ${si.eka} add ${si.karanna}`,
  editEvent: `Event ${si.eka} edit ${si.karanna}`,
  eventTitle: `Event ${si.eka}`,
  eventDate: `Date ${si.eka}`,
  saveEvent: `Event ${si.eka} save ${si.karanna}`,
  cancel: `Cancel ${si.karanna}`,
  deleteEvent: `Delete ${si.karanna}`,
  noUpcomingEvent: `Next event ${si.ekak} ${si.nehae}`,
  nextEventIn: "{title} \u00b7 {date} \u00b7 {n} days",
  nextEventToday: `{title} \u00b7 {date} \u00b7 ${si.ada}`,
  yearDayLabel: "{year} \u00b7 Day {day}",
  dailyQuiz: "Daily Quiz",
  dailyQuizHint: `${si.ada} AI quiz \u2014 ${si.hema} ${si.dawasama} ${si.aluthen} ${si.wenawa}`,
  startDailyQuiz: `Start ${si.karanna}`,
  dailyQuizDone: `${si.ada} quiz ${si.eka} done`,
  dailyQuizPreparing: `${si.ada} quiz AI ${si.eken} ${si.hadenawa}...`,
  dailyStreak: "Daily streak",
  growthSpeed: "Growth speed",
  growthSlow: "Slow",
  growthSteady: "Steady",
  growthFast: "Fast",
  dailyQuestions: "Daily questions",
  dailyQuestionsHint: `Subjects ${si.kihipayak} cover ${si.wenna} daily questions add ${si.karanna}.`,
  addDailyQuestion: `Question ${si.eka} add ${si.karanna}`,
  editQuestion: `Question ${si.eka} edit ${si.karanna}`,
  saveQuestion: `Question ${si.eka} save ${si.karanna}`,
  questionPrompt: `Question ${si.eka}`,
  optionLabel: "Option {n}",
  correctAnswer: `${si.hari} answer ${si.eka}`,
  explanation: `${si.wisthara} ${si.kirima}`,
  dailyQuestionsEmpty: `Daily questions ${si.nehae}. ${si.aluth} question ${si.ekak} add ${si.karanna}.`,
  mixedSubjects: "Subjects mix",
  dailyQuizEmptyBank: `${si.ada} quiz ready ${si.nehae}. App ${si.eka} open ${si.karala} wait ${si.karanna}, ${si.ho} ClassGenie ${si.eken} questions add ${si.karanna}.`,
  allSubjects: "All",
  subject: "Subject",
  dailyQuizStudentHint: `AI ${si.eka} ${si.oyage} results ${si.saha} papers ${si.balala} ${si.ada} quiz ${si.hadanna}. ${si.dawasa} ${si.wenas} ${si.unoth} ${si.aluthen} ${si.hadenawa}.`,
  questionCount: "Questions {n}",
  subjectScores: `Subject ${si.eken} score`,
  coveredSubjects: "Subjects",
  submitAnswer: `Submit ${si.karanna}`,
  howItWasSolved: `${si.wisthara} ${si.kirima}`,
  dailyQuizOnce: `${si.ada} quiz ${si.eka} ${si.dawasata} ${si.eka} ${si.parak} ${si.witharayi}.`,
  guideLearning: "Guide learning",
  guideLearningHint: `Full syllabus ${si.eka} step by step. Done ${si.una} ${si.tika} home donut ${si.ekata} ${si.enawa}.`,
  subjectTimeChart: `Subject score ${si.saha} time`,
  chartTime: "Time",
  syllabusDone: `Syllabus ${si.eken} done`,
  wastedTime: "Wasted time",
  swipeCharts: `Slide ${si.eka} side ${si.ekata} swipe ${si.karanna}`,
  noSubjectData: `Past papers ${si.saha} model papers summary ${si.eken} ${si.enawa}.`,
  markDone: `Done ${si.karanna}`,
  undoDone: "Undo",
  estimatedMin: "~{n} min",
  openGuide: "Guide learning",
  hoursAbbrev: "h",
  minutesAbbrev: "min",
  chartScore: "Score",
  papers: "Papers",
  pastPapers: "Past papers",
  modelPapers: "Model papers",
  createOwnPapers: "Create own papers",
  papersHint: `Past papers ${si.saha} model papers ${si.karala} score ${si.saha} time home chart ${si.ekata} ${si.enawa}.`,
  startPaper: `Start ${si.karanna}`,
  noPapers: `Papers ${si.nehae}.`,
  paperYear: "Year",
  selectSubject: `Subject select ${si.karanna}`,
  selectYear: `Year select ${si.karanna}`,
  pickSubjectYear: `Subject ${si.saha} year select ${si.karala} paper ${si.eka} ${si.enawa}.`,
  paperTitle: "Paper title",
  savePaper: `Paper ${si.eka} save ${si.karanna}`,
  paperSaved: `Paper save ${si.una}.`,
  addPaperQuestion: `Question ${si.eka} add ${si.karanna}`,
  createOwnHint: `Mokak hari topic ${si.ekak} type ${si.karanna}. Example: Science Newton ${si.niyama} ${si.kotasa} ${si.amarui}. Questions count ${si.deela} generate ${si.karanna} \u2014 Daily Quiz ${si.wage} ${si.hadenawa}.`,
  createOwnPlaceholder: `Science ${si.eke} Newton ${si.niyama} ${si.kotasa} ${si.amarui}. Questions 10k ${si.hadala} ${si.denna}.`,
  generatePaper: `Questions generate ${si.karanna}`,
  ownPaperPrompt: "Topic / request",
  paperQuestionCount: "Questions",
  lastPaperScore: "Last score {n}%",
  navTasks: "Tasks",
  navStudy: "Study",
  navGame: "Game",
  navBio: "Bio",
  tasksTitle: "Tasks",
  tasksHint: `AI ${si.eka} ${si.oyage} quiz, study, games, papers ${si.balala} ${si.ada} tasks ${si.hadanna}. Daily Quiz ${si.hema} ${si.dawasama}.`,
  addTask: `Task add ${si.karanna}`,
  taskPlaceholder: `Ex: Science Newton ${si.niyama} revise ${si.karanna}`,
  noTasks: `${si.ada} tasks ${si.nehae}.`,
  tasksPreparing: `${si.ada} tasks AI ${si.eken} ${si.hadenawa}...`,
  changeTasks: `Tasks change ${si.karanna}`,
  taskChangeHint: `Task ${si.ekak} ${si.yanna} bari ${si.unoth} AI ${si.ekata} kiyanna.`,
  taskChangePlaceholder: `Ex: Past papers ${si.karanna} time ${si.nehae}.`,
  openTask: "Open",
  studyTitle: "Study",
  studyHint: `Subject select ${si.karala}, ${si.ilagata} ${si.padama} select ${si.karanna}.`,
  startStudy: `Study start ${si.karanna}`,
  wantToLearn: "What do you want to learn?",
  studyChatHint: `Subject ${si.eka} select ${si.karala} ${si.padama} ${si.eka} tap ${si.karanna}. AI ${si.eka} ${si.padama} ${si.eka} step by step ${si.ahanna}.`,
  studyPlaceholder: `Check ${si.ekata} answer ${si.eka} type ${si.karanna}.`,
  studyPickSubject: `Subject ${si.eka} select ${si.karanna}`,
  studyPickLesson: `${si.padama} select ${si.karanna}`,
  lesson: si.padama,
  lessons: si.padam,
  backToSubjects: "Subjects",
  backToLessons: si.padam,
  startLesson: `${si.padama} start ${si.karanna}`,
  previousChats: "Previous chats",
  newStudyChat: "New chat",
  noStudyChats: `Chats ${si.nehae}.`,
  openChats: `Chats open ${si.karanna}`,
  closeChats: `Chats close ${si.karanna}`,
  lessonPercent: "{n}%",
  partProgress: `${si.kotasa} {a}/{b}`,
  loadOlderChats: `Parana messages load ${si.karanna}`,
  partQuizReady: `Quiz ready`,
  openPartQuiz: `Quiz open ${si.karanna}`,
  lessonComplete: `${si.padama} ${si.iwarayi}`,
  resumeLesson: `Continue ${si.karanna}`,
  learned: "Learned",
  gameTitle: "Game",
  gameHint: `Quick questions ${si.tika} game ${si.wage} try ${si.karanna}.`,
  playGame: `Play ${si.karanna}`,
  playAgain: `Play ${si.ayeth}`,
  bioTitle: "Bio",
  bioHint: `Name, grade, medium, ${si.saha} subjects ${si.me} ${si.eken} update ${si.karanna}.`,
  tapSubjects: `Subjects tap ${si.karala} select ${si.karanna}.`,
  studyMedium: "School medium",
  studyMediumHint: `Lankawe subjects Sinhala, English, ${si.ho} Tamil medium ${si.eken} ${si.ugannwanna}. ${si.oyage} medium select ${si.karanna}.`,
  mediumSinhala: "Sinhala medium",
  mediumEnglish: "English medium",
  mediumTamil: "Tamil medium",
};

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
writeFileSync(
  join(root, "lib", "copy-singlish.json"),
  JSON.stringify(singlish, null, 2) + "\n",
  "utf8",
);
console.log("wrote lib/copy-singlish.json", Object.keys(singlish).length);
